### ISSUE TITLE
For all blog posts, add further metadata

### ISSUE THREAD

**Issue by TimDaub** [rugpullindex/content-system#7]
## Scope

- In the `/blog` folder are all the project's blog posts.
- On top of each post, before the `---` termination sequence, data can be defined as YAML, e.g. `title`. But potentially, there are many other options of metadata that can be defined
- Check this file for an example: https://raw.githubusercontent.com/rugpullindex/content-system/4be2810cdc4d941ba21f6f8b1ba62fdf11f1c636/blog/2021-02-23/the-algorithm-its-working.md

```
title: The Algorithm; It's Working!
oldTitle: TheAlgorithmItsWorking
---

On Feb 18, 2021, the maintainer of the "[Oceancap - Datapool Evaluation and
Charting"
```

## Deliverables

- For each blog post, in the YAML define 3-5 keywords for each post and add as a list called `keywords`
- Define the authors as a list called `authors`
- If the post contains images, take the first image link and define it as  `image`

NOTE: This metadata is important for further SEO of the site.

## Time estimate

- It's time-intensive when done with care.
- 4h

**Comment by il3ven** [comment]
I am starting to work on this. I hope someone else isn't working on this right now.
